import 'package:flutter/material.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('fa'));
  }

  bool get isFa => locale.languageCode == 'fa';

  String translate(String key) {
    return (isFa ? _fa[key] : _en[key]) ?? key;
  }

  // Getters for common app strings
  String get appTitle => translate('appTitle');
  String get home => translate('home');
  String get calendar => translate('calendar');
  String get tasks => translate('tasks');
  String get goals => translate('goals');
  String get projects => translate('projects');
  String get habits => translate('habits');
  String get notes => translate('notes');
  String get focus => translate('focus');
  String get reviews => translate('reviews');
  String get analytics => translate('analytics');
  String get settings => translate('settings');

  String get todayWorkload => translate('todayWorkload');
  String get timeline => translate('timeline');
  String get topCommitments => translate('topCommitments');
  String get startFocus => translate('startFocus');
  String get disciplineScore => translate('disciplineScore');
  String get planningAccuracy => translate('planningAccuracy');
  String get commitmentReliability => translate('commitmentReliability');
  String get quickCreate => translate('quickCreate');
  String get newTask => translate('newTask');
  String get newGoal => translate('newGoal');
  String get newHabit => translate('newHabit');
  String get newProject => translate('newProject');
  String get newNote => translate('newNote');
  String get minutes => translate('minutes');
  String get hours => translate('hours');
  String get dailyReviewTitle => translate('dailyReviewTitle');
  String get weeklyReviewTitle => translate('weeklyReviewTitle');
  String get energyLevel => translate('energyLevel');
  String get focusScore => translate('focusScore');
  String get saveReview => translate('saveReview');

  static final Map<String, String> _fa = {
    'appTitle': 'ZedPlan',
    'home': 'خانه',
    'calendar': 'تقویم',
    'tasks': 'وظایف',
    'goals': 'اهداف',
    'projects': 'پروژه‌ها',
    'habits': 'عادت‌ها',
    'notes': 'یادداشت‌ها',
    'focus': 'تمرکز',
    'reviews': 'ارزیابی',
    'analytics': 'تحلیل',
    'settings': 'تنظیمات',
    'todayWorkload': 'فشار کاری امروز',
    'timeline': 'جدول زمانی',
    'topCommitments': 'تعهدات اصلی',
    'startFocus': 'شروع تمرکز',
    'disciplineScore': 'امتیاز دیسیپلین',
    'planningAccuracy': 'دقت برنامه‌ریزی',
    'commitmentReliability': 'پایبندی به تعهدات',
    'quickCreate': 'ایجاد سریع',
    'newTask': 'وظیفه جدید',
    'newGoal': 'هدف جدید',
    'newHabit': 'عادت جدید',
    'newProject': 'پروژه جدید',
    'newNote': 'یادداشت جدید',
    'goodMorning': 'صبح بخیر',
    'goodAfternoon': 'عصر بخیر',
    'goodEvening': 'شب بخیر',
    'estimated': 'تخمینی',
    'actual': 'واقعی',
    'minutes': 'دقیقه',
    'hours': 'ساعت',
    'completed': 'تکمیل شده',
    'postponed': 'به تعویق افتاده',
    'inProgress': 'در حال انجام',
    'pending': 'در انتظار',
    'overloadWarning': 'برنامه شما امروز بیش از حد ظرفیت به نظر می‌رسد.',
    'reviewSchedule': 'بررسی جدول زمانی',
    'keepAnyway': 'ادامه برنامه',
    'dailyReviewTitle': 'ارزیابی و انعکاس روزانه',
    'weeklyReviewTitle': 'ارزیابی استراتژیک هفتگی',
    'energyLevel': 'سطح انرژی',
    'focusScore': 'امتیاز تمرکز',
    'mainObstacles': 'موانع اصلی',
    'tomorrowPriorities': 'اولویت‌های فردا',
    'saveReview': 'ثبت ارزیابی',
    'searchPlaceholder': 'جستجوی کامل در وظایف، اهداف، یادداشت‌ها...',
    'backupRestore': 'پشتیبان‌گیری و بازیابی',
    'exportData': 'خروجی داده‌ها (JSON)',
    'importData': 'ورودی داده‌ها (JSON)',
    'languageRtl': 'زبان و راست‌چین',
    'appearance': 'ظاهر برنامه',
    'lightMode': 'روشن',
    'darkMode': 'تاریک',
    'systemMode': 'پیروی از سیستم',
    // Calendar screen
    'calendarSchedule': 'تقویم و زمان‌بندی',
    'viewDay': 'روز',
    'view3Day': '۳ روز',
    'viewWeek': 'هفته',
    'viewMonth': 'ماه',
    'capacityWarning': 'هشدار ظرفیت',
    'capacityWarningDetail': 'برنامه از ظرفیت مفید روز بیشتر است',
    'capacityBreakdown': 'تحلیل ظرفیت روز',
    'plannedTime': 'زمان برنامه‌ریزی‌شده',
    'usefulCapacity': 'ظرفیت مفید روز',
    'categorySplit': 'توزیع بر اساس دسته',
    'capacitySuggestion':
        'پیشنهاد بازنگری: آیا می‌توانید یک مورد را حذف یا به فردا منتقل کنید؟ ظرفیت مفید روز حدود ۶.۵ ساعت است.',
    'close': 'بستن',
    'details': 'جزئیات',
    'startTime': 'زمان شروع',
    'duration': 'مدت زمان',
    'category': 'دسته',
    'deleteBlock': 'حذف این بلوک',
    'editBlock': 'ویرایش',
    'blockDeleted': 'بلوک زمانی حذف شد',
    'noBlocksTitle': 'برنامه‌ای برای این روز ثبت نشده',
    'noBlocksSubtitle':
        'با یک بلوک زمانی ساده شروع کنید؛ برنامه‌ریزی واقع‌بینانه از همین‌جا آغاز می‌شود.',
    'addTimeBlock': 'افزودن بلوک زمانی',
    'today': 'امروز',
    'deepWork': 'کار عمیق',
    'meeting': 'جلسه',
    'review': 'بازبینی',
    // Common
    'save': 'ذخیره',
    'cancel': 'انصراف',
    'delete': 'حذف',
    'edit': 'ویرایش',
    'confirm': 'تأیید',
    'add': 'افزودن',
    'undo': 'بازگردانی',
    'next': 'بعدی',
    'back': 'قبلی',
    'getStarted': 'شروع کنیم',
    'viewAll': 'مشاهده همه',
    // Onboarding
    'onboardTitle1': 'برنامه‌ریزی واقع‌بینانه',
    'onboardBody1':
        'وظایف، بلوک‌های زمانی و تعهدات خود را در یک تقویم هوشمند بچینید و ظرفیت روز خود را بشناسید.',
    'onboardTitle2': 'تمرکز عمیق',
    'onboardBody2':
        'با تایمر تمرکز، ثبت وقفه‌ها و آمار واقعی، روی کارهای مهم تمرکز کنید نه فقط مشغول بودن.',
    'onboardTitle3': 'بازبینی و رشد',
    'onboardBody3':
        'هر روز و هر هفته عملکرد خود را مرور کنید؛ سیستم الگوهای رفتاری شما را به شما نشان می‌دهد.',
    'onboardNameTitle': 'چه نامی داشته باشیم؟',
    'onboardNameSubtitle': 'برای شخصی‌سازی تجربه، نام خود را وارد کنید.',
    'onboardNameHint': 'نام شما...',
    'onboardThemeTitle': 'حالت نمایش را انتخاب کنید',
    'onboardThemeSubtitle': 'هر زمان بخواهید می‌توانید در پروفایل تغییرش دهید.',
    'lightLabel': 'روشن',
    'darkLabel': 'تاریک',
    'systemLabel': 'سیستم',
    // Profile & settings
    'profileTitle': 'پروفایل و تنظیمات',
    'editName': 'ویرایش نام',
    'nameHint': 'نام نمایشی...',
    'statTasksDone': 'وظایف انجام‌شده',
    'statFocusMinutes': 'دقیقه تمرکز',
    'statBestStreak': 'بهترین زنجیره',
    'appearanceSection': 'ظاهر',
    'calendarSection': 'تقویم',
    'securitySection': 'امنیت',
    'lockAppLabel': 'قفل برنامه',
    'biometricLabel': 'استفاده از اثر انگشت/چهره',
    'changePinLabel': 'تغییر پین',
    'newPinLabel': 'پین جدید',
    'confirmPinLabel': 'تکرار پین',
    'pinValidationError': 'پین باید ۴ رقم باشد و با تکرار آن یکسان باشد',
    'pinSaved': 'پین جدید ذخیره شد',
    'appLockedTitle': 'برنامه قفل است',
    'scanToUnlock': 'برای باز کردن، اثر انگشت یا چهره را اسکن کنید',
    'enterPinToUnlock': 'پین ۴ رقمی را وارد کنید',
    'unlockWithBiometric': 'باز کردن با بیومتریک',
    'biometricFailed': 'احراز هویت بیومتریک ناموفق بود',
    'pinInvalid': 'پین وارد شده اشتباه است',
    'jalaliLabel': 'هجری شمسی (جلالی)',
    'gregorianLabel': 'میلادی',
    // Time blocks
    'timeConflictError':
        'تداخل زمانی: این بازه با بلوک «%s» هم‌پوشانی دارد. زمان دیگری انتخاب کنید.',
    'addCategory': 'دسته جدید',
    'categoryNameHint': 'نام دسته (مثال: ورزش)',
    'categoryExists': 'این دسته قبلاً ثبت شده است',
    'newCategoryAdded': 'دسته جدید اضافه شد',
    'allDay': 'شبانه‌روز',
    // Habits on home
    'habitsTodayTitle': 'عادت‌های امروز',
    'allHabitsDone': 'همه عادت‌های امروز انجام شد! آفرین.',
    // Goals / projects editing
    'descriptionLabel': 'توضیحات',
    'editProject': 'ویرایش پروژه',
    'editGoal': 'ویرایش هدف',
    'noDescriptionYet': 'بدون توضیح',
    // Task estimate
    'estimateHint': 'دقیقه (مثال: ۴۵)',
    'invalidEstimate': 'زمان تخمینی باید عددی مثبت باشد',
    // Theme color
    'themeColor': 'رنگ برنامه',
    // Block outcome
    'markDone': 'انجام شد',
    'markNotDone': 'انجام نشد',
    'recordNotDoneReason': 'ثبت دلیل انجام‌نشده',
    'outcomeSection': 'نتیجه این بلوک',
    // Distractions
    'distractionsTitle': 'ثبت حواس‌پرتی',
    'distractionSubtitle': 'چه عاملی حواستان را پرت کرد؟',
    'addReason': 'دلیل جدید',
    'reasonNameHint': 'نام دلیل (مثال: سر و صدا)',
    'reasonExists': 'این دلیل قبلاً ثبت شده است',
    'reasonAdded': 'دلیل جدید اضافه شد',
    'distractionRecorded': 'حواس‌پرتی ثبت شد',
    'weeklyDistractions': 'حواس‌پرتی هفتگی',
    'topReasons': 'شایع‌ترین دلایل',
    'times': 'بار',
    'noDistractions': 'هفته‌ای بدون حواس‌پرتی ثبت‌شده — عالی!',
    'reasonPhone': 'موبایل و شبکه‌های اجتماعی',
    'reasonLowEnergy': 'خستگی و کم‌انرژی',
    'reasonEnvironment': 'حواس‌پرتی محیطی',
    'reasonUnexpected': 'کار غیرمنتظره',
    'reasonClarity': 'کمبود شفافیت کار',
    'reasonMotivation': 'انگیزه پایین',
    'reasonOther': 'سایر',
    // Notifications
    'notificationsSection': 'اعلان‌ها',
    'notificationsLabel': 'اعلان‌های زمان‌بندی و یادآور روزانه',
    'notificationsDesc':
        'شروع و پایان بلوک‌های زمانی، ثبت نتیجه و جمع‌بندی پایان روز',
    'blockEndAlarmLabel': 'آلارم پایان بلوک',
    'blockEndAlarmDesc': 'برای اعلان پایان بلوک، صدای هشدار قوی پخش شود',
    'languageSection': 'زبان',
    'aboutSection': 'درباره',
    'aboutBody':
        'ZedPlan یک برنامه‌ریز آفلاین با تمرکز بر رفتار و خودمدیریتی است. نسخه 1.0.0',
    'resetData': 'پاک کردن همه داده‌ها',
    'resetConfirmTitle': 'همه داده‌ها پاک شود؟',
    'resetConfirmBody':
        'این عمل غیرقابل بازگشت است و همه وظایف، عادت‌ها و یادداشت‌های شما حذف می‌شود.',
    'nameSaved': 'نام ذخیره شد',
    'dataCleared': 'همه داده‌ها پاک شد',
    // Tasks
    'tasksTitle': 'وظایف من',
    'addTask': 'وظیفه جدید',
    'taskTitleHint': 'عنوان وظیفه...',
    'emptyTasksTitle': 'هنوز وظیفه‌ای ندارید',
    'emptyTasksMessage':
        'اولین وظیفه خود را بسازید؛ برنامه‌ریزی واقعی از همین‌جا شروع می‌شود.',
    'filterAll': 'همه',
    'filterPending': 'در انتظار',
    'filterDone': 'انجام‌شده',
    'priorityLow': 'کم',
    'priorityMedium': 'متوسط',
    'priorityHigh': 'زیاد',
    'estimatedLabel': 'زمان تخمینی',
    'priorityLabel': 'اولویت',
    'taskDeleted': 'وظیفه حذف شد',
    'taskDetailTitle': 'جزئیات وظیفه',
    'editTaskTitle': 'ویرایش عنوان',
    'noDescription': 'توضیحی ثبت نشده است.',
    'startFocusForTask': 'شروع تمرکز روی این وظیفه',
    // Calendar add block
    'addBlockTitle': 'بلوک زمانی جدید',
    'blockTitleHint': 'عنوان بلوک...',
    'startTimeLabel': 'ساعت شروع',
    'durationLabel': 'مدت',
    'blockAdded': 'بلوک زمانی اضافه شد',
    'blockAddedMultiple': '%s بلوک زمانی اضافه شد',
    'timeBlock': 'بلوک زمانی',
    'dateLabel': 'تاریخ',
    'hoursUnit': 'ساعت',
    'repeatLabel': 'تکرار',
    'repeatNone': 'بدون تکرار',
    'repeatDaily': 'روزانه',
    'repeatEveryOtherDay': 'یک روز در میان',
    'repeatWeekly': 'هفتگی',
    'repeatBiweekly': 'دو هفته یک‌بار',
    'repeatMonthly': 'ماهانه',
    // Habits
    'habitsTitle': 'عادت‌ها و استمرار',
    'emptyHabitsTitle': 'عادتی ثبت نشده است',
    'emptyHabitsMessage': 'یک عادت کوچک اضافه کنید؛ استمرار مهم‌تر از شدت است.',
    'addHabit': 'عادت جدید',
    'habitTitleHint': 'عنوان عادت...',
    'streakLabel': 'زنجیره',
    'day': 'روز',
    'last30Days': '۳۰ روز اخیر',
    'doneToday': 'امروز انجام شد',
    // Notes
    'notesTitle': 'یادداشت‌ها',
    'emptyNotesTitle': 'یادداشتی وجود ندارد',
    'emptyNotesMessage': 'افکار و ایده‌های خود را ثبت کنید تا فراموش نشوند.',
    'addNote': 'یادداشت جدید',
    'noteTitleHint': 'عنوان...',
    'noteBodyHint': 'متن یادداشت...',
    'noteSaved': 'یادداشت ذخیره شد',
    'noteDeleted': 'یادداشت حذف شد',
    'searchNotes': 'جستجو در یادداشت‌ها...',
    // Goals
    'goalsTitle': 'اهداف و چشم‌انداز',
    'emptyGoalsTitle': 'هدفی تعریف نشده است',
    'emptyGoalsMessage':
        'اهداف خود را مشخص کنید تا اقدامات روزانه معنا پیدا کنند.',
    'addGoal': 'هدف جدید',
    'goalTitleHint': 'عنوان هدف...',
    'progress': 'پیشرفت',
    // Projects
    'projectsTitle': 'پروژه‌ها',
    'emptyProjectsTitle': 'پروژه‌ای وجود ندارد',
    'emptyProjectsMessage':
        'پروژه‌های خود را بسازید و پیشرفت‌شان را دنبال کنید.',
    'addProject': 'پروژه جدید',
    'projectTitleHint': 'عنوان پروژه...',
    // Focus
    'focusTodayStat': 'تمرکز امروز',
    'sessionsStat': 'جلسه',
    'minutesStat': 'دقیقه',
    'pickTask': 'انتخاب وظیفه',
    'noTasksForFocus': 'وظیفه‌ای برای تمرکز وجود ندارد',
    'focusRecorded': 'جلسه تمرکز ثبت شد',
    // Reviews
    'accomplishments': 'دستاوردهای امروز',
    'reviewSavedOk': 'ارزیابی روز ذخیره شد',
    'emptyWeeklyTitle': 'داده کافی برای تحلیل هفتگی نیست',
    'emptyWeeklyMessage':
        'بعد از چند روز استفاده، خلاصه هفتگی شما اینجا ساخته می‌شود.',
    // Analytics
    'analyticsTitle': 'تحلیل رفتاری',
    'analyticsSubtitle': 'شناخت ریتم شخصی',
    'emptyAnalyticsTitle': 'هنوز داده‌ای برای تحلیل نیست',
    'emptyAnalyticsMessage':
        'با افزودن وظیفه، تمرکز یا عادت، نمودارهای واقعی شما اینجا شکل می‌گیرد.',
    'focusByCategory': 'توزیع زمان بر اساس نوع فعالیت',
    'weeklyFocus': 'تمرکز هفتگی (دقیقه)',
    'executionRate': 'نرخ اجرا',
    'noCategoryData': 'فعالیتی برنامه‌ریزی نشده است',
    // Home
    'workloadEmpty': 'امروز وظیفه‌ای ثبت نشده است. با یک وظیفه کوچک شروع کنید.',
    'workloadProgress': 'از وظایف امروز کامل شده',
    'timelineEmpty': 'برنامه‌ای برای امروز ثبت نشده است.',
    'timelineToday': 'خط زمانی امروز',
    'emptyBlocksCalendar': 'برنامه‌ای برای این روز ثبت نشده',
    'addTaskCta': 'ساخت وظیفه',
    'goToCalendar': 'رفتن به تقویم',
    'tasksCountShort': '%s کار',

    // Achievements & Gamification
    'achievements': 'دستاوردها و نشان‌ها',
    'achievementsSubtitle': 'نشان‌ها و رتبه‌های دیسیپلین و خودمدیریتی شما',
    'unlockedBadge': 'دستاورد آزاد شد!',
    'allCategories': 'همه',
    'catDiscipline': 'دیسیپلین',
    'catFocus': 'تمرکز',
    'catHabits': 'عادت‌ها',
    'catPlanning': 'برنامه‌ریزی',
    'catMastery': 'تسلط',
    'tierBronze': 'برنز',
    'tierSilver': 'نقره',
    'tierGold': 'طلا',
    'tierDiamond': 'الماس',
    'levelTitle': 'سطح دیسیپلین',
    'totalPoints': 'امتیاز دستاورد',
    'unlockedOf': '%s از %s آزاد شده',
    'tapForDetails': 'لمس برای مشاهده جزئیات',
    'lockedDescription': 'این دستاورد هنوز قفل است. با استمرار در فعالیت آن را آزاد کنید.',
    'nextTier': 'سطح بعدی: %s',
    'maxTierReached': 'بالاترین سطح (الماس) کسب شد!',
    'unlockedOn': 'دریافت شده در %s',
    'recentAchievements': 'دستاوردها و نشان‌های اخیر',
    'viewAllAchievements': 'مشاهده تالار افتخارات',

    // Achievement catalog items
    'ach_task_finisher_title': 'تمام‌کننده وظایف',
    'ach_task_finisher_desc': 'تکمیل وظایف با اراده و پشتکار',
    'ach_commitment_title': 'پایبند به تعهدات',
    'ach_commitment_desc': 'تکمیل وظایف ستاره‌دار و تعهدات اصلی روزانه',
    'ach_zero_postpone_title': 'اراده آنی (بدون تعویق)',
    'ach_zero_postpone_desc': 'انجام کارها بدون به تعویق انداختن به روز بعد',
    'ach_daily_streak_title': 'زنجیره روزانه',
    'ach_daily_streak_desc': 'روزهای متوالی تکمیل تمام برنامه‌های روز',
    'ach_focus_master_title': 'استاد کار عمیق',
    'ach_focus_master_desc': 'مجموع دقایق ثبت‌شده در تایمر تمرکز',
    'ach_deep_unbroken_title': 'تمرکز خدشه‌ناپذیر',
    'ach_deep_unbroken_desc': 'جلسات تمرکز کامل بدون حتی یک وقفه و حواس‌پرتی',
    'ach_focus_marathon_title': 'ماراتن تمرکز',
    'ach_focus_marathon_desc': 'طولانی‌ترین جلسه تمرکز پیوسته',
    'ach_habit_builder_title': 'سازنده روتین',
    'ach_habit_builder_desc': 'تعریف و پیگیری عادت‌های سازنده',
    'ach_habit_streak_title': 'پادشاه استمرار',
    'ach_habit_streak_desc': 'طولانی‌ترین زنجیره انجام مداوم یک عادت',
    'ach_perfect_habit_day_title': 'روز بی‌نقص',
    'ach_perfect_habit_day_desc': 'روزهایی که ۱۰۰٪ عادت‌های فعال تیک خوردند',
    'ach_time_blocker_title': 'معمار زمان',
    'ach_time_blocker_desc': 'طراحی و چیدمان بلوک‌های زمانی در تقویم',
    'ach_outcome_tracker_title': 'ارزیاب نتایج',
    'ach_outcome_tracker_desc': 'ثبت بازخورد و نتیجه برای بلوک‌های زمانی',
    'ach_reflector_title': 'اهل بازبینی و تأمل',
    'ach_reflector_desc': 'ثبت گزارش‌های انعکاس روزانه در پایان روز',
    'ach_goal_setter_title': 'چشم‌اندازساز',
    'ach_goal_setter_desc': 'ترسیم اهداف بلندمدت و معنادار',
    'ach_note_collector_title': 'شکارچی ایده‌ها',
    'ach_note_collector_desc': 'ثبت ایده‌ها، یادداشت‌ها و تفکرات',
    'ach_discipline_master_title': 'استاد دیسیپلین',
    'ach_discipline_master_desc': 'رسیدن به بالاترین امتیاز دیسیپلین و انضباط فردی',

    // New Analytics
    'dailyCompletionTrend': 'روند تکمیل وظایف (۷ روز اخیر)',
    'habitStreaksRanking': 'رتبه‌بندی استمرار عادت‌ها',
    'activeStreak': 'زنجیره فعال',
    'focusTimeDistribution': 'الگوی تمرکز در ساعات شبانه‌روز',
    'morningFocus': 'صبح (۵ تا ۱۲)',
    'afternoonFocus': 'بعدازظهر (۱۲ تا ۱۷)',
    'eveningFocus': 'عصر و غروب (۱۷ تا ۲۲)',
    'nightFocus': 'شب (۲۲ تا ۵)',
    'tasksByPriority': 'وضعیت اجرا بر اساس اولویت',
    'estimationAccuracy': 'دقت تخمین زمان',
    'accurateEstimation': 'تخمین‌های شما بسیار واقع‌بینانه است.',
    'underEstimation': 'معمولاً کارها بیشتر از تخمین شما طول می‌کشد. زمان بیشتری برای بلوک‌ها در نظر بگیرید.',
    'overEstimation': 'معمولاً سریع‌تر از تخمین کارها را تمام می‌کنید.',
    'energyVsOutput': 'همبستگی سطح انرژی و خروجی',
    'smartInsights': 'بینش‌ها و الگوهای هوشمند رفتاری',
    'insightPeakTimeTitle': 'زمان طلایی تمرکز شما',
    'insightPeakTimeDesc': 'بیشترین میزان کار عمیق شما در بازه «%s» ثبت شده است. کارهای کلیدی را در این زمان برنامه‌ریزی کنید.',
    'insightDisciplineHigh': 'دیسیپلین شما در عالی‌ترین سطح است! این ثبات و تعهد رشک‌برانگیز است.',
    'insightDisciplineMed': 'پیشرفت شما پیوسته و خوب است. با تمرکز بر تعهدات ستاره‌دار به سطح الماس برسید.',
    'insightDisciplineLow': 'برای ساخت دیسیپلین پایدار، امروز فقط روی ۱ وظیفه اصلی و ۱ عادت کوچک تمرکز کنید.',
    'disciplineScoreHeader': 'شاخص دیسیپلین فردی',
    'disciplineScoreDesc': 'محاسبه‌شده بر اساس نرخ اجرا، پایبندی به تعهد، ثبات عادت و تمرکز',
  };

  static final Map<String, String> _en = {
    'appTitle': 'ZedPlan',
    'home': 'Home',
    'calendar': 'Calendar',
    'tasks': 'Tasks',
    'goals': 'Goals',
    'projects': 'Projects',
    'habits': 'Habits',
    'notes': 'Notes',
    'focus': 'Focus',
    'reviews': 'Reviews',
    'analytics': 'Analytics',
    'settings': 'Settings',
    'todayWorkload': "Today's Workload",
    'timeline': 'Timeline',
    'topCommitments': 'Top Commitments',
    'startFocus': 'Start Focus',
    'disciplineScore': 'Discipline Score',
    'planningAccuracy': 'Planning Accuracy',
    'commitmentReliability': 'Commitment Reliability',
    'quickCreate': 'Quick Create',
    'newTask': 'New Task',
    'newGoal': 'New Goal',
    'newHabit': 'New Habit',
    'newProject': 'New Project',
    'newNote': 'New Note',
    'goodMorning': 'Good Morning',
    'goodAfternoon': 'Good Afternoon',
    'goodEvening': 'Good Evening',
    'estimated': 'Estimated',
    'actual': 'Actual',
    'minutes': 'min',
    'hours': 'hrs',
    'completed': 'Completed',
    'postponed': 'Postponed',
    'inProgress': 'In Progress',
    'pending': 'Pending',
    'overloadWarning': 'Your schedule looks unusually full today.',
    'reviewSchedule': 'Review Schedule',
    'keepAnyway': 'Keep Anyway',
    'dailyReviewTitle': 'Daily Reflection & Review',
    'weeklyReviewTitle': 'Weekly Strategic Review',
    'energyLevel': 'Energy Level',
    'focusScore': 'Focus Score',
    'mainObstacles': 'Main Obstacles',
    'tomorrowPriorities': "Tomorrow's Priorities",
    'saveReview': 'Save Review',
    'searchPlaceholder': 'Search tasks, goals, notes...',
    'backupRestore': 'Backup & Restore',
    'exportData': 'Export Data (JSON)',
    'importData': 'Import Data (JSON)',
    'languageRtl': 'Language & Layout',
    'appearance': 'Appearance',
    'lightMode': 'Light',
    'darkMode': 'Dark',
    'systemMode': 'System',
    // Calendar screen
    'calendarSchedule': 'Calendar & Scheduling',
    'viewDay': 'Day',
    'view3Day': '3-Day',
    'viewWeek': 'Week',
    'viewMonth': 'Month',
    'capacityWarning': 'Capacity warning',
    'capacityWarningDetail': 'Your plan exceeds the useful capacity of the day',
    'capacityBreakdown': 'Daily Capacity Breakdown',
    'plannedTime': 'Planned time',
    'usefulCapacity': 'Useful daily capacity',
    'categorySplit': 'Split by category',
    'capacitySuggestion':
        'Review suggestion: can you remove or move one item to tomorrow? Useful daily capacity is around 6.5 hours.',
    'close': 'Close',
    'details': 'Details',
    'startTime': 'Start time',
    'duration': 'Duration',
    'category': 'Category',
    'deleteBlock': 'Delete this block',
    'editBlock': 'Edit',
    'blockDeleted': 'Time block deleted',
    'noBlocksTitle': 'Nothing scheduled for this day',
    'noBlocksSubtitle':
        'Start with one simple time block — realistic planning starts here.',
    'addTimeBlock': 'Add time block',
    'today': 'Today',
    'deepWork': 'Deep Work',
    'meeting': 'Meeting',
    'review': 'Review',
    // Common
    'save': 'Save',
    'cancel': 'Cancel',
    'delete': 'Delete',
    'edit': 'Edit',
    'confirm': 'Confirm',
    'add': 'Add',
    'undo': 'Undo',
    'next': 'Next',
    'back': 'Back',
    'getStarted': 'Get Started',
    'viewAll': 'View all',
    // Onboarding
    'onboardTitle1': 'Plan realistically',
    'onboardBody1':
        'Organize tasks, time blocks and commitments in a smart calendar and know your daily capacity.',
    'onboardTitle2': 'Deep focus',
    'onboardBody2':
        'With a focus timer, interruption logging and real stats — work on what matters, not just staying busy.',
    'onboardTitle3': 'Reflect & grow',
    'onboardBody3':
        'Review your days and weeks; the system reveals your behavioral patterns back to you.',
    'onboardNameTitle': 'What should we call you?',
    'onboardNameSubtitle': 'Enter your name to personalize the experience.',
    'onboardNameHint': 'Your name...',
    'onboardThemeTitle': 'Choose your appearance',
    'onboardThemeSubtitle': 'You can change this anytime from your profile.',
    'lightLabel': 'Light',
    'darkLabel': 'Dark',
    'systemLabel': 'System',
    // Profile & settings
    'profileTitle': 'Profile & Settings',
    'editName': 'Edit name',
    'nameHint': 'Display name...',
    'statTasksDone': 'Tasks done',
    'statFocusMinutes': 'Focus minutes',
    'statBestStreak': 'Best streak',
    'appearanceSection': 'Appearance',
    'calendarSection': 'Calendar',
    'securitySection': 'Security',
    'lockAppLabel': 'Lock app',
    'biometricLabel': 'Use fingerprint/face ID',
    'changePinLabel': 'Change PIN',
    'newPinLabel': 'New PIN',
    'confirmPinLabel': 'Confirm PIN',
    'pinValidationError': 'PIN must be 4 digits and match confirmation',
    'pinSaved': 'PIN saved',
    'appLockedTitle': 'App locked',
    'scanToUnlock': 'Scan your fingerprint/face to unlock',
    'enterPinToUnlock': 'Enter your 4-digit PIN',
    'unlockWithBiometric': 'Unlock with biometric',
    'biometricFailed': 'Biometric authentication failed',
    'pinInvalid': 'Incorrect PIN',
    'jalaliLabel': 'Jalali (Solar Hijri)',
    'gregorianLabel': 'Gregorian',
    // Time blocks
    'timeConflictError':
        'Time conflict: this range overlaps with "%s". Pick another time.',
    'addCategory': 'New category',
    'categoryNameHint': 'Category name (e.g. Workout)',
    'categoryExists': 'This category already exists',
    'newCategoryAdded': 'Category added',
    'allDay': '24 hours',
    // Habits on home
    'habitsTodayTitle': 'Today\'s habits',
    'allHabitsDone': 'All of today\'s habits are done. Nice!',
    // Goals / projects editing
    'descriptionLabel': 'Description',
    'editProject': 'Edit project',
    'editGoal': 'Edit goal',
    'noDescriptionYet': 'No description',
    // Task estimate
    'estimateHint': 'minutes (e.g. 45)',
    'invalidEstimate': 'Estimated time must be a positive number',
    // Theme color
    'themeColor': 'App color',
    // Block outcome
    'markDone': 'Done',
    'markNotDone': 'Not done',
    'recordNotDoneReason': 'Record why it wasn\'t done',
    'outcomeSection': 'Block outcome',
    // Distractions
    'distractionsTitle': 'Log a distraction',
    'distractionSubtitle': 'What pulled your attention away?',
    'addReason': 'New reason',
    'reasonNameHint': 'Reason name (e.g. noise)',
    'reasonExists': 'This reason already exists',
    'reasonAdded': 'Reason added',
    'distractionRecorded': 'Distraction recorded',
    'weeklyDistractions': 'Weekly distractions',
    'topReasons': 'Top reasons',
    'times': 'times',
    'noDistractions': 'A week with no recorded distractions — great!',
    'reasonPhone': 'Phone & social media',
    'reasonLowEnergy': 'Tiredness / low energy',
    'reasonEnvironment': 'Environmental noise',
    'reasonUnexpected': 'Unexpected work',
    'reasonClarity': 'Lack of clarity',
    'reasonMotivation': 'Low motivation',
    'reasonOther': 'Other',
    // Notifications
    'notificationsSection': 'Notifications',
    'notificationsLabel': 'Schedule alerts & daily reminder',
    'notificationsDesc':
        'Block start/end prompts, outcome submission, and the end-of-day wrap-up',
    'blockEndAlarmLabel': 'Block end alarm',
    'blockEndAlarmDesc': 'Play a louder alarm sound for end-of-block reminders',
    'languageSection': 'Language',
    'aboutSection': 'About',
    'aboutBody':
        'ZedPlan is an offline planner focused on behavior and self-management. Version 1.0.0',
    'resetData': 'Clear all data',
    'resetConfirmTitle': 'Clear all data?',
    'resetConfirmBody':
        'This cannot be undone. All tasks, habits and notes will be deleted.',
    'nameSaved': 'Name saved',
    'dataCleared': 'All data cleared',
    // Tasks
    'tasksTitle': 'My Tasks',
    'addTask': 'New task',
    'taskTitleHint': 'Task title...',
    'emptyTasksTitle': 'No tasks yet',
    'emptyTasksMessage':
        'Create your first task — realistic planning starts here.',
    'filterAll': 'All',
    'filterPending': 'Pending',
    'filterDone': 'Done',
    'priorityLow': 'Low',
    'priorityMedium': 'Medium',
    'priorityHigh': 'High',
    'estimatedLabel': 'Estimated time',
    'priorityLabel': 'Priority',
    'taskDeleted': 'Task deleted',
    'taskDetailTitle': 'Task details',
    'editTaskTitle': 'Edit title',
    'noDescription': 'No description yet.',
    'startFocusForTask': 'Start focus on this task',
    // Calendar add block
    'addBlockTitle': 'New time block',
    'blockTitleHint': 'Block title...',
    'startTimeLabel': 'Start time',
    'durationLabel': 'Duration',
    'blockAdded': 'Time block added',
    'blockAddedMultiple': '%s time blocks added',
    'timeBlock': 'Time block',
    'dateLabel': 'Date',
    'hoursUnit': 'hrs',
    'repeatLabel': 'Repeat',
    'repeatNone': 'None',
    'repeatDaily': 'Daily',
    'repeatEveryOtherDay': 'Every other day',
    'repeatWeekly': 'Weekly',
    'repeatBiweekly': 'Biweekly',
    'repeatMonthly': 'Monthly',
    // Habits
    'habitsTitle': 'Habits & consistency',
    'emptyHabitsTitle': 'No habits yet',
    'emptyHabitsMessage': 'Add one small habit — consistency beats intensity.',
    'addHabit': 'New habit',
    'habitTitleHint': 'Habit title...',
    'streakLabel': 'Streak',
    'day': 'days',
    'last30Days': 'Last 30 days',
    'doneToday': 'Done today',
    // Notes
    'notesTitle': 'Notes',
    'emptyNotesTitle': 'No notes yet',
    'emptyNotesMessage':
        'Capture your thoughts and ideas so they are not lost.',
    'addNote': 'New note',
    'noteTitleHint': 'Title...',
    'noteBodyHint': 'Note content...',
    'noteSaved': 'Note saved',
    'noteDeleted': 'Note deleted',
    'searchNotes': 'Search notes...',
    // Goals
    'goalsTitle': 'Goals & vision',
    'emptyGoalsTitle': 'No goals defined',
    'emptyGoalsMessage': 'Define your goals so daily actions gain meaning.',
    'addGoal': 'New goal',
    'goalTitleHint': 'Goal title...',
    'progress': 'Progress',
    // Projects
    'projectsTitle': 'Projects',
    'emptyProjectsTitle': 'No projects yet',
    'emptyProjectsMessage': 'Create projects and track their progress.',
    'addProject': 'New project',
    'projectTitleHint': 'Project title...',
    // Focus
    'focusTodayStat': 'Focused today',
    'sessionsStat': 'sessions',
    'minutesStat': 'min',
    'pickTask': 'Pick a task',
    'noTasksForFocus': 'No task to focus on',
    'focusRecorded': 'Focus session recorded',
    // Reviews
    'accomplishments': 'Accomplishments today',
    'reviewSavedOk': 'Daily review saved',
    'emptyWeeklyTitle': 'Not enough data for weekly analysis',
    'emptyWeeklyMessage':
        'After a few days of use, your weekly summary will appear here.',
    // Analytics
    'analyticsTitle': 'Behavioral analytics',
    'analyticsSubtitle': 'Know your personal rhythm',
    'emptyAnalyticsTitle': 'No data to analyze yet',
    'emptyAnalyticsMessage':
        'Add a task, focus session or habit and your real charts will take shape here.',
    'focusByCategory': 'Time split by activity type',
    'weeklyFocus': 'Weekly focus (minutes)',
    'executionRate': 'Execution rate',
    'noCategoryData': 'Nothing planned yet',
    // Home
    'workloadEmpty': 'Nothing planned today. Start with one small task.',
    'workloadProgress': 'of today\'s tasks completed',
    'timelineEmpty': 'Nothing scheduled for today.',
    'timelineToday': 'Today\'s timeline',
    'emptyBlocksCalendar': 'Nothing scheduled for this day',
    'addTaskCta': 'Create a task',
    'goToCalendar': 'Go to calendar',
    'tasksCountShort': '%s tasks',

    // Achievements & Gamification
    'achievements': 'Achievements & Badges',
    'achievementsSubtitle': 'Your discipline & self-management milestones',
    'unlockedBadge': 'Achievement Unlocked!',
    'allCategories': 'All',
    'catDiscipline': 'Discipline',
    'catFocus': 'Focus',
    'catHabits': 'Habits',
    'catPlanning': 'Planning',
    'catMastery': 'Mastery',
    'tierBronze': 'Bronze',
    'tierSilver': 'Silver',
    'tierGold': 'Gold',
    'tierDiamond': 'Diamond',
    'levelTitle': 'Discipline Level',
    'totalPoints': 'Achievement Points',
    'unlockedOf': '%s of %s unlocked',
    'tapForDetails': 'Tap to view details',
    'lockedDescription': 'This achievement is currently locked. Keep progressing to unlock it.',
    'nextTier': 'Next tier: %s',
    'maxTierReached': 'Maximum Diamond Tier Achieved!',
    'unlockedOn': 'Unlocked on %s',
    'recentAchievements': 'Recent Achievements & Badges',
    'viewAllAchievements': 'View Hall of Fame',

    // Achievement catalog items
    'ach_task_finisher_title': 'Task Finisher',
    'ach_task_finisher_desc': 'Complete tasks consistently with willpower',
    'ach_commitment_title': 'Commitment Champion',
    'ach_commitment_desc': 'Complete star-marked primary daily commitments',
    'ach_zero_postpone_title': 'Zero Postponement',
    'ach_zero_postpone_desc': 'Execute tasks on the same day without postponing',
    'ach_daily_streak_title': 'Daily Streak',
    'ach_daily_streak_desc': 'Consecutive days with 100% daily tasks completed',
    'ach_focus_master_title': 'Deep Focus Master',
    'ach_focus_master_desc': 'Total deep focus minutes logged in timer',
    'ach_deep_unbroken_title': 'Unbroken Focus',
    'ach_deep_unbroken_desc': 'Focus sessions with zero interruptions or distractions',
    'ach_focus_marathon_title': 'Focus Marathon',
    'ach_focus_marathon_desc': 'Longest continuous focus session',
    'ach_habit_builder_title': 'Habit Builder',
    'ach_habit_builder_desc': 'Build and track positive daily habits',
    'ach_habit_streak_title': 'Consistency King',
    'ach_habit_streak_desc': 'Longest continuous streak on any single habit',
    'ach_perfect_habit_day_title': 'Perfect Habit Day',
    'ach_perfect_habit_day_desc': 'Days where 100% of active habits were completed',
    'ach_time_blocker_title': 'Time Architect',
    'ach_time_blocker_desc': 'Design and schedule time blocks on the calendar',
    'ach_outcome_tracker_title': 'Outcome Tracker',
    'ach_outcome_tracker_desc': 'Submit execution outcomes for your scheduled blocks',
    'ach_reflector_title': 'Deep Reflector',
    'ach_reflector_desc': 'Complete daily evening reviews and reflections',
    'ach_goal_setter_title': 'Visionary',
    'ach_goal_setter_desc': 'Define meaningful vision and strategic goals',
    'ach_note_collector_title': 'Idea Collector',
    'ach_note_collector_desc': 'Capture thoughts, notes, and insights',
    'ach_discipline_master_title': 'Discipline Master',
    'ach_discipline_master_desc': 'Reach the highest composite self-discipline score',

    // New Analytics
    'dailyCompletionTrend': 'Task Completion Trend (Last 7 Days)',
    'habitStreaksRanking': 'Habit Streaks & Consistency',
    'activeStreak': 'Active Streak',
    'focusTimeDistribution': 'Focus Rhythm Across the Day',
    'morningFocus': 'Morning (5am - 12pm)',
    'afternoonFocus': 'Afternoon (12pm - 5pm)',
    'eveningFocus': 'Evening (5pm - 10pm)',
    'nightFocus': 'Night (10pm - 5am)',
    'tasksByPriority': 'Execution by Priority Level',
    'estimationAccuracy': 'Time Estimation Accuracy',
    'accurateEstimation': 'Your time estimates are highly balanced and realistic.',
    'underEstimation': 'Tasks tend to take longer than estimated. Allow extra buffer in time blocks.',
    'overEstimation': 'You typically finish tasks faster than estimated.',
    'energyVsOutput': 'Energy Level vs Output Correlation',
    'smartInsights': 'Smart Behavioral Insights',
    'insightPeakTimeTitle': 'Your Peak Focus Window',
    'insightPeakTimeDesc': 'Your deepest focus occurs during "%s". Schedule high-priority work during this window.',
    'insightDisciplineHigh': 'Your discipline is at the highest level! Your consistency is exemplary.',
    'insightDisciplineMed': 'Good steady progress. Focus on your starred commitments to reach Diamond tier.',
    'insightDisciplineLow': 'To build enduring discipline, start today with just 1 key task and 1 small habit.',
    'disciplineScoreHeader': 'Discipline Index',
    'disciplineScoreDesc': 'Calculated from execution rate, commitment reliability, habit streak & focus',
  };
}

class AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['fa', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(AppLocalizationsDelegate old) => false;
}
